- ztz_web/src/components/products/ProductDetailForm.vue
- ztz_web/src/router/index.js
- ztz_web/src/views/products/ProductDetailView.vue
**작업 완료**
- 상품 상세 페이지
- 구매 수량 선택 기능
- 장바구니 및 바로 구매 버튼
> feat:[김가람] 특정한 권한 없이 모든 사용자가 판매 리스트에서 상품 클릭 시 보는 상품의 상세 페이지 UI[ZTZ-WEB-UI7]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/products/ProductsController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsServiceImpl.java
- ztz_web/src/components/products/ProductDetailForm.vue
- ztz_web/src/components/products/ProductList.vue
- ztz_web/src/router/index.js
- ztz_web/src/store/actions.js
- ztz_web/src/views/products/ProductDetailView.vue
**작업완료**
> 백엔드[ZTZ_PROCESS12]
- 상품 정보 프론트로 전달(컨트롤러, 서비스)
> 프론트엔드 [ZTZ-WEB-UI12]
- 상품 정보 spring 요청
- 화면 반영 확인 완료
> feat: [김가람] 상품리스트에서 상품 클릭 시 해당 상품의 정보를 가져오기 위한 시스템[ZTZ_PROCESS12]

- ztz_process/build.gradle
- ztz_web/src/components/mypage/MyPageProfileSection.vue
- ztz_web/src/main.js
- ztz_web/src/store/actions.js
- ztz_web/src/views/WorkView.vue
- 누락된 redis implementation 추가
- 테스트용 콘솔 코드 삭제
- 원본 통합을 위한 actions 코드 일부 삭제 및 수정
> feat:[임보경] 원본 통합을 위한 코드 수정

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/member/MemberController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/member/MemberService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/member/MemberServiceImpl.java
- ztz_web/src/store/actions.js
- 기존의 products 에서 ztz/products로 경로 수정
> feat: [임보경] 프론트에서 전달받은 토큰으로 사용자를 찾아 반환하는 시스템[ZTZ-PROCESS16]

- ztz_web/src/components/products/ProductDetailForm.vue
- ztz_web/src/components/products/ProductList.vue
- ztz_web/src/components/products/ProductReviewContents.vue
- ztz_web/src/components/products/ProductReviewForm.vue
- ztz_web/src/main.js
- ztz_web/src/store/actions.js
**작업완료**
- 상품 리뷰 form 
- 상품 리뷰 content
- 페이지네이션
- 페이지네이션 main.js에 추가
> feat:[김가람] 특정한 권한없이 모든 사용자가 상품 상세 페이지 내에서 볼 수 있는 상품 리뷰 UI[ZTZ-WEB-UI8]

- ztz_web/src/css/initialization.css
- ztz_web/src/css/mypage.css
- ztz_web/src/css/products.css
- ztz_web/src/views/mypage/MypageView.vue
- ztz_web/src/views/products/ProductsView.vue
-  CSS 분리
- 초기화 CSS 필요한 컴포넌트에만 따로 적용
> feat:[임보경] 컴포넌트 별 스타일 독립성을 위한 CSS 분리작업 [ZTZ-WEB-UI24]

- ztz_web/src/components/common/header/MainHeader.vue
Backlog
- [O]  SubMenubar 컴포넌트 구성
- [O]  비로그인의 경우 “안녕하세요, 회원님” 문구가 출력되고 로그인한 경우 “환영합니다, xxx님” 문구가 출력되도록 배치
> feat [박근수] : 메인페이지에서 SubMenubar & 로그인/비로그인 시의 문구 Header UI[ZTZ-WEB-UI25]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/order/CartController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/order/request/AddCartRequest.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/order/Cart.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/order/CartItem.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/order/CartItemRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/order/CartRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/order/CartService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/order/CartServiceImpl.java
- ztz_process/src/test/java/kr/eddi/ztz_process/OrderTestCase.java
작업내역
- 장바구니 아이템 저장 시스템
- 장바구니 아이템 리스트 조회시스템
작업예정
- 장바구니 아이템 저장 UI
- 장바구니 아이템 조회 UI
> feat:[박진주] 로그인 회원이 장바구니 넣기 버튼 클릭 시 상품을 장바구니 DB에 저장하는 시스템[ZTZ-PROCESS9]

- ztz_web/src/components/products/ProductDetailForm.vue
- ztz_web/src/components/products/review/ProductReviewContents.vue
- ztz_web/src/components/products/review/ProductReviewForm.vue
- ztz_web/src/components/products/review/ReviewRegisterForm.vue
작업 완료
- 리뷰 등록 버튼
- 리뷰 등록 버튼 클릭 시 리뷰 등록 form 팝업
> feat:[김가람] 상품을 구매한 사용자가 리뷰 등록 버튼 클릭 시 보는 리뷰 등록 UI [ZTZ-WEB-UI23]

- ztz_web/src/components/account/SignUpForm.vue
- ztz_web/src/components/common/AddressForm.vue
- ztz_web/src/main.js
- ztz_web/src/views/account/SignUpView.vue
어디서나 공통으로 사용 가능한 주소 정보를 입력받는 컴포넌트 [ZTZ-WEB-UI19]
- 주소 등록 form UI 작성
- 해당하는 값들이 변경될때 마다 사용하는 페이지로 값 전달
회원 가입 버튼을 눌렀을 때 맴버프로필 정보(주소,전화번호)를 입력하는 UI [ZTZ-WEB-UI26]
- 회원 가입 UI 수정
- 회원 가입 정보 전달값 추가 작성
> feat: [최재민]회원 가입 버튼을 눌렀을 때 맴버프로필 정보(주소,전화번호)를 입력하는 UI [ZTZ-WEB-UI26]

- ztz_web/public/index.html
- ztz_web/src/components/mypage/MyPageContentSection.vue
- ztz_web/src/components/mypage/MyPageProfileSection.vue
- ztz_web/src/components/reservation/FoundryCard.vue
- ztz_web/src/components/reservation/FoundryList.vue
- ztz_web/src/css/foundry.css
- ztz_web/src/css/initialization.css
- ztz_web/src/css/mypage.css
- ztz_web/src/main.js
- ztz_web/src/router/index.js
- ztz_web/src/views/reservation/FoundryView.vue
**특정한 권한이 필요없이 접근 가능한 양조장 메인 UI[ZTZ-WEB-UI22]**
-  양조장 투어 및 체험 메인 UI
-  협약된(설정) 양조장 리스트 컴포넌트
-  1개의 양조장 정보를 가지고 있는 양조장 컴포넌트
**CSS 코드 재사용성을 위한 CSS 파일 분리 [ZTZ-WEB-UI35]**
- 양조장 UI를 하면서 마이페이지와 공통으로 뺄 수 있는 스타일 분리 및 수정
**로그인한 사용자만 볼 수 있는 양조장 투어 예약하기 버튼 [ZTZ-WEB-UI34]**
- 로그인한 사용자만 예약하기 버튼을 볼 수 있도록 기능 추가
> feat: [임보경] 특정한 권한이 필요없이 접근 가능한 양조장 메인 UI[ZTZ-WEB-UI22]

- ztz_web/src/components/mypage/MyPageProfileSection.vue
- ztz_web/src/components/products/review/ProductReviewForm.vue
- ztz_web/src/components/products/review/ReviewRegisterForm.vue
리뷰 기능 fix- 파일 포함여부 null 체크에서 length로 변경
회원탈퇴 update- 회원탈퇴여부 및 확인메시지 추가
> fix:[박진주] 상품을 주문한 회원이 리뷰 작성 시 리뷰 게시판에 등록하는 시스템 [ZTZ-PROCESS25]

- ztz_web/src/router/index.js
- ztz_web/src/views/account/SignUpView.vue
- 작업내역
- 누락된 회원가입 정보 추가
- 현재 작업중인 관리자페이지 router 경로 제거
> fix:[박진주]관리자회원의 정보를 확인하고 회원 가입시켜주는 UI[ZTZ-WEB-UI52]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/CommentRequest.java
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/QuestionCommentController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/QuestionComment.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionCommentService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionCommentServiceImpl.java
- ztz_web/src/components/boards/comment/QuestionCommentList.vue
- ztz_web/src/components/boards/comment/QuestionCommentRegisterForm.vue
- ztz_web/src/router/index.js
- ztz_web/src/store/actions.js
- ztz_web/src/views/boards/QuestionReadView.vue
등록된 게시글에 보여지는 작성된 댓글을 삭제 클릭 시 요청되는 게시글 삭제 UI [ZTZ-WEB-UI32]
- [O]  댓글 삭제 버튼 버튼 구현
- [O]  이메일과 작성자가 같을때 삭제 가능하도록 구현
- [O]  삭제를 확인하는 알림창 UI가 나오도록 구현
- [O]  댓글 삭제를 요청하는 actions 구현
등록된 질문 게시글에 등록한 댓글을 삭제하는 시스템 [ZTZ-PROCESS24]
- [O]  삭제된 댓글의 번호를 받아와 삭제 구현
- [O]  댓글 삭제 컨트롤러 구현
> feat [박근수] : 등록된 게시글에 보여지는 작성된 댓글을 삭제 클릭 시 요청되는 게시글 삭제 UI [ZTZ-WEB-UI32]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/tour/ReservationController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/tour/FoundryService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/tour/FoundryServiceImpl.java
- ztz_web/src/components/mypage/MyPageProfileSection.vue
- ztz_web/src/components/mypage/MyReservationDetailSection.vue
- ztz_web/src/components/tour/ReservationModifyForm.vue
- ztz_web/src/css/foundry.css
- ztz_web/src/css/initialization.css
- ztz_web/src/router/index.js
- ztz_web/src/store/actions.js
- ztz_web/src/views/mypage/MypageView.vue
- ztz_web/src/views/tour/ModifyView.vue
[ZTZ-PROCESS59]
예약 수정 시스템 추가
[ZTZ-WEB-UI85]
예약 수정 UI 추가
[ZTZ-WEB-UI89]
마이페이지에서 내 예약건수 보이는 UI
> feat: [임보경] 예약 수정 UI 및 시스템 완료

- ztz_web/package.json
- ztz_web/src/components/main/MainPageProductList.vue
- ztz_web/src/main.js
> update: [김가람] 메인 페이지 UI 내의 상품 리스트에 캐러셀 기능 추가[ZTZ-WEB-UI70]

- ztz_app/android/app/build.gradle
- ztz_app/lib/api/account/login_api.dart
- ztz_app/lib/api/account/sign_up_api.dart
- ztz_app/lib/api/account/sign_up_infos/account_state.dart
- ztz_app/lib/api/account/sign_up_infos/manager_sign_up_info.dart
- ztz_app/lib/api/account/sign_up_infos/member_sign_up_info.dart
- ztz_app/lib/components/account/login_component.dart
- ztz_app/lib/components/account/sign_up_component.dart
- ztz_app/lib/components/text_filed/common_text_filed.dart
- ztz_app/lib/pages/account/first_page.dart
- ztz_app/lib/pages/account/login_page.dart
- ztz_app/lib/pages/account/signup_page.dart
- ztz_app/lib/utility/text_field_validate.dart
- ztz_app/lib/utility/text_styles.dart
- ztz_app/pubspec.yaml
1. 로그인 UI 완성 및 기능 테스트 완료
2. 맴버 회원가입, 관리자 회원가입 완료
> feat: [최재민] : 회원가입 및 로그인 UI 완성

- ztz_web/src/components/mypage/MyPageReviewForm.vue
- ztz_web/src/components/mypage/OrderDetailForm.vue
- ztz_web/src/components/products/review/ProductReviewForm.vue
**작업내역**
- 기존 상품 상세 페이지에 있던 리뷰 등록 기능을 마이페이지 내의 주문관리로 이동
> update: [김가람] 구매자 회원이 구매 확정 후 클릭할 수 있는 리뷰 작성 UI [ZTZ-WEB-UI 96]

- ztz_web/src/components/mypage/OrderDetailForm.vue
- ztz_web/src/components/products/review/ReviewRegisterForm.vue
**작업내역**
- 리뷰 dialog 창이 열리지 않는 오류 수정
> fix: [김가람] 구매자 회원이 구매 확정 후 클릭할 수 있는 리뷰 작성 UI [ZTZ-WEB-UI 96]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/QuestionCommentController.java
- ztz_web/src/components/boards/comment/QuestionCommentRegisterForm.vue
- ztz_web/src/store/actions.js
- ztz_web/src/views/boards/QuestionReadView.vue
추가) 일반 사용자가 아닌 관리자 권한으로 댓글 등록해야 한다.
> fix [박근수] : 등록된 게시글에 보여지는 댓글을 등록하는 UI [ZTZ-WEB-UI75]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/products/ProductsController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/tour/ReservationController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/products/Product.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/products/ProductsRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsServiceImpl.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/tour/FoundryService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/tour/FoundryServiceImpl.java
- ztz_process/src/test/java/kr/eddi/ztz_process/ProductsListTest.java
- ztz_process/src/test/java/kr/eddi/ztz_process/ReservationTestCase.java
- ztz_web/src/components/common/header/MainHeader.vue
- ztz_web/src/components/managerpage/AllReservationDetailSection.vue
- ztz_web/src/components/managerpage/ManagerPageNaviTabs.vue
- ztz_web/src/components/managerpage/ManagerPageProfileSection.vue
- ztz_web/src/components/managerpage/ProductManagementList.vue
- ztz_web/src/components/month/MonthDrinkProductList.vue
- ztz_web/src/components/mypage/MyPageProfileSection.vue
- ztz_web/src/components/order/CartForm.vue
- ztz_web/src/components/products/ProductModifyForm.vue
- ztz_web/src/components/products/ProductRegisterForm.vue
- ztz_web/src/store/actions.js
- ztz_web/src/views/month/MonthDrinkView.vue
- ztz_web/src/views/products/ProductsView.vue
작업내역
- 이달의 술 등록 UI/백엔드
- 이달의 술 조회 UI/백엔드
- 양조장 전체 예약리스트 조회 UI/백엔드
> feat:[박진주]관리자 회원의 이달의 술 등록 시스템[ZTZ-PROCESS58]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/tour/ReservationController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/tour/FoundryServiceImpl.java
> fix:[박진주]관리자 회원의 전체 회원 예약리스트 조회시스템[ZTZ-PROCESS55]

- ztz_web/src/components/mypage/MyReservationDetailSection.vue
선결제 완료 시 예약 취소 버튼이 사용자에게 보이지 않도록 숨기는 기능 추가
> update: [임보경] 양조장 예약 선 결제 시 예약 취소 버튼이 사용자에게 보이지 않도록 UI 변경[ZTZ-WEB-UI98]

- ztz_app/lib/components/account/login_component.dart
- ztz_app/lib/components/layout/bottom_bar.dart
- ztz_app/lib/pages/home_page.dart
- ztz_app/lib/pages/splash/splash_screen_page.dart
**작업내역**
- 하단 네이게이션바
- 메인페이지 / 검색 / 마이페이지 연결
> feat: [김가람] 메인 화면에서 보이는 하단 네비게이션 바 UI [ZTZ-APP-UI15]

- ztz_app/lib/components/category/category_form.dart
- ztz_app/lib/components/layout/bottom_bar.dart
- ztz_app/lib/components/layout/menu_app_bar.dart
- ztz_app/lib/pages/category/category_page.dart
**작업내역**
- 바텀 네비 바에 카테고리 버튼 추가
- 카테고리 페이지 연결
카테고리 내의 각 페이지는 연결 필요함
> feat: [김가람] 모든 사용자가 하단 네비게이션 바에서 카테고리 클릭 시 보는 카테고리 UI [ZTZ-APP-UI19]

- ztz_app/lib/components/account/login_component.dart
- ztz_app/lib/components/main_page_components/todays_recommend_component.dart
- ztz_app/lib/components/product/product_detail/product_detail_appbar.dart
- ztz_app/lib/components/product/product_detail/product_detail_component.dart
- ztz_app/lib/controller/account/member_api.dart
- ztz_app/lib/controller/account/sign_up_infos/account_state.dart
- ztz_app/lib/controller/product/product_controller.dart
- ztz_app/lib/controller/product/product_infos/product_info.dart
- ztz_app/lib/pages/main_page/main_page.dart
- ztz_app/lib/pages/product/product_detail_page.dart
- ztz_app/lib/pages/splash/splash_screen_page.dart
- 로그인 상태 관리
- 상품 정보와 리뷰 정보 불러오는 시점 리팩토링
- member 정보 요청하는 api 작성 완료
> feat : [최재민] GetX를 활용한 로그인 상태 관리 UI[ZTZ-APP-UI21]

- ztz_web/src/components/managerpage/ManagerPageNaviTabs.vue
- ztz_web/src/components/mypage/MyPageNaviTabs.vue
- ztz_web/src/components/mypage/MyPageProfileModify.vue
- ztz_web/src/store/actions.js
- ztz_web/src/store/index.js
- [O]  회원정보 변경 UI 구성(현재 비밀번호, 새 비밀번호, 핸드폰 번호 입력창)
- [O]  변경이 완료되면 “회원정보 변경이 완료되었습니다” 라는 알림창이 출력되고 메인페이지로 돌아간다.
- [O]  component-MyPageProfileModify 구현
- [O]  라우터 연결
> feat [박근수] : 로그인한 사용자가 마이페이지에 회원정보변경 클릭시 보여지는 회원정보변경 리스트 작성 UI [ZTZ-WEB-UI95]

- ztz_web/src/components/order/OrderInfoForm.vue
- ztz_web/src/views/products/ProductsView.vue
- 작업내역
서버에서 order_info 추가로 orderPrice 보내는 값 웹에서  추가
> fix:[박진주]관리자 회원의 매출조회 UI[ZTZ-WEB-UI94]

- ztz_app/lib/components/my_page/my_page_form.dart
- ztz_app/lib/controller/order/order_controller.dart
- ztz_app/lib/controller/order/order_infos/order_info.dart
- ztz_app/lib/controller/reivew/review_controller.dart
- ztz_app/lib/pages/my_page/my_page.dart
- ztz_app/lib/utility/text_styles.dart
- 마이페이지 UI 
- 로그인 여부 확인
- 비로그인 -> 로그인페이지
- 로그인 -> 마이페이지
- 로그인 마이페이지에서 리뷰, 주문 정보 불러오기
> feat: [김가람] 하단 네비게이션 바에서 마이페이지 클릭 시 보는 마이페이지 UI [ZTZ-APP-UI20]

- ztz_app/lib/components/my_page/my_page_form.dart
**작업내역**
마이페이지 진입 시 사용자 값이 null이 나오는 오류 수정
> fix: [김가람] 마이페이지 진입 시 null값이 나오는 오류 수정[ZTZ-APP-UI20]

- ztz_app/lib/components/layout/menu_app_bar.dart
- ztz_app/lib/components/layout/white_menu_app_bar.dart
**작업 내용**
- 기존 초록색 상단 앱 바 elevation 수정
- 하얀색 상단 앱 바 추가
> update: [김가람] 앱 내에서 사용하는 각 메뉴별 하얀색 상단 바 추가 [ZTZ-APP-UI16]

- ztz_app/lib/components/account/login_component.dart
- ztz_app/lib/components/account/sign_up_component.dart
- ztz_app/lib/components/layout/bottom_bar.dart
- ztz_app/lib/components/layout/main_app_bar.dart
- ztz_app/lib/components/layout/menu_app_bar.dart
- ztz_app/lib/components/layout/white_menu_app_bar.dart
- ztz_app/lib/components/my_page/my_page_form.dart
- ztz_app/lib/components/text_filed/common_text_filed.dart
- ztz_app/lib/pages/account/login_page.dart
- ztz_app/lib/pages/account/signup_page.dart
- ztz_app/lib/pages/my_page/my_page.dart
- ztz_app/lib/utility/text_styles.dart
**작업내역**
- 마이페이지 진입 시 로그인 페이지가 순간적으로 보이는 이슈 수정
- 바텀 바에서 페이지 연결 시 로그인 여부를 확인
- 로그인 UI에 상단 앱 바 추가 및 UI 수정
- 로그인 성공 후 homepage로 이동 시 navigator 수정
- 회원가입 UI에 상단 앱 바 추가 및 토글 색상 수정
> fix: [김가람] 로그인한 사용자가 마이페이지 진입 시 로그인 페이지가 보이는 UI 수정 [ZTZ-APP-UI25]

- ztz_web/src/components/common/AddressForm.vue
- ztz_web/src/components/mypage/MyPageDeliverySection.vue
> fix:[박진주]어디서나 공통으로 사용 가능한 주소 정보를 입력받는 컴포넌트 [ZTZ-WEB-UI19]

- ztz_process/src/main/java/kr/eddi/ztz_process/entity/products/Review.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/products/ReviewRepository.java
- ztz_process/src/test/java/kr/eddi/ztz_process/ReviewTestCase.java
**작업내역**
- 리뷰 엔티티에서 멤버, 상품 맵핑 시 fetch 타입 lazy로 변경
- fetch 타입 변경에 따라 query문 수정
- 리뷰 테스트 수정
> fix: [김가람] Review 엔티티 Fecth Eager에서 Lazy로 코드 수정 [ZTZ-PROCESS25]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/products/ProductsController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/products/request/ProductLocalAndTypeRequest.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/order/OrderInfo.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/order/Payment.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/order/PaymentState.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/order/OrderInfoRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/products/ProductsRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/order/OrderServiceImpl.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsServiceImpl.java
- ztz_web/src/components/managerpage/AllOrderDetailForm.vue
- ztz_web/src/components/managerpage/AllOrderManagement.vue
- ztz_web/src/components/mypage/OrderDetailForm.vue
- ztz_web/src/components/mypage/OrderManagement.vue
- 주문 결제 정보 매핑 정보 eager -> lazy로 변경
- 주문 정보 state string -> enum으로 수정
- 제조지역과 알코올 타입 기반 상품 정보 리스트 반환 시스템
> fix : [최재민] 주문 결제 정보 eager -> lazy로 수정 완료[ZTZ-PROCESS15]

- ztz_app/lib/components/my_page/my_page_form.dart
- ztz_app/lib/controller/account/member_api.dart
- ztz_app/lib/controller/account/member_modify_infos/modify_address_info.dart
- ztz_app/lib/controller/account/sign_up_infos/account_state.dart
- ztz_app/lib/pages/my_page/modify_address_page.dart
- ztz_app/lib/utility/button_style.dart
- ztz_app/lib/utility/text_styles.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/order/OrderController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/member/MemberServiceImpl.java
**작업 내역**
- 배송지 관리 UI
- memberProfile의 주소 정보 가져오기
- 서버에 배송지 수정 요청 
- 주소 수정 인포 
- 주소 수정 api
- 결제 정보 요청 시 플러터 뷰 토큰값 판별 코드 수정
- 배송지 주소 수정 요청 시 토큰값 판별 코드 수정
> feat: [김가람] 마이페이지에서 배송지 관리 목록 클릭 시 보는 배송지 관리 UI[ZTZ-APP-UI36]

- ztz_app/lib/components/order/cart_list_builder.dart
- ztz_app/lib/components/order/cart_list_item.dart
- ztz_app/lib/controller/order/api/order_service_api.dart
- ztz_app/lib/controller/order/cart_controller.dart
- ztz_app/lib/pages/cart.dart
- ztz_app/lib/utility/text_styles.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/tour/form/ReservationForm.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/tour/Reservation.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/tour/FoundryServiceImpl.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/tour/request/ReservationRequest.java
- ztz_web/src/components/mypage/MyReservationDetailSection.vue
- ztz_web/src/components/tour/CompleteReservationCard.vue
- ztz_web/src/components/tour/ReservationForm.vue
- ztz_web/src/components/tour/ReservationModifyForm.vue
앱 카트 UI 작업
- ZTZ-APP-UI 38~43
웹, 서버 예약 수정
- ZTZ-WEB-UI 99
- ZTZ-PROCESS65
> feat: [임보경] 앱 카트 UI 작업 및 코드리뷰로 인한 예약쪽 코드 수정(웹, 서버)

- ztz_app/lib/components/account/sign_up_component.dart
- ztz_app/lib/controller/account/sign_up_api.dart
- ztz_app/lib/utility/button_style.dart
- ztz_app/lib/utility/text_field_decoration.dart
- ztz_app/lib/utility/text_field_validate.dart
- ztz_app/lib/utility/text_styles.dart
**작업내역**
- 회원가입 UI 수정
-텍스트필드 스타일 수정
- 버튼 스타일 수정
- authorityName 수정
> style: [김가람] 회원가입 UI 수정 [ZTZ-APP-UI9]

- ztz_app/lib/components/my_page/board/register_question_form.dart
- ztz_app/lib/controller/board/board_controller.dart
- ztz_app/lib/controller/board/board_infos/register_question_info.dart
- ztz_app/lib/pages/my_page/modify_address_page.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/BoardsRequest.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/BoardCategory.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/BoardCategoryType.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/QuestionBoard.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionServiceImpl.java
- ztz_web/src/components/boards/QuestionRegisterForm.vue
- ztz_web/src/store/actions.js
- ztz_web/src/views/boards/QuestionListView.vue
**앱**
- 1:1문의 게시물 등록 UI 및 api
- 배송지 관리 스타일 수정
**웹**
- 서버에 질문게시판 등록 요청 시 카테고리 및 멤버 id 추가
- 질문 게시판 리스트 가운데 정렬 수정
**백**
- 카테고리 엔티티 추가
- 질문 등록 시 서비스임플 기능 수정
> feat: [김가람] 사용자가 질문 게시판에서 게시물 등록 시 카테고리를 추가하는 시스템[ZTZ-PROCESS66]

- ztz_app/lib/components/my_page/board/question_board_list.dart
- ztz_app/lib/components/my_page/my_page_form.dart
- ztz_app/lib/controller/board/board_controller.dart
- ztz_app/lib/controller/board/board_infos/board_info.dart
- ztz_app/lib/pages/my_page/board/question_board_page.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/QuestionController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/boards/QuestionRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionServiceImpl.java
**작업내역**
- 1:1문의 게시판 리스트 UI
- 멤버별 게시판 리스트 불러오는 시스템
> feat: [김가람] 마이페이지에서 1:1 문의 클릭 시 보는 1:1문의 리스트 UI[ZTZ-APP-UI47]

- ztz_app/lib/components/order/cart_list_item.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/service/order/CartService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/order/CartServiceImpl.java
> fix: [임보경] 카트 담기 중복 체크 기능 수정

- ztz_web/src/components/common/footer/footer.vue
- [O]  Footer UI에서의 Admin 버튼 구현
- [O]  비로그인&일반 사용자 :  Q&A 컴포넌트 버튼만 구현
- [O]  관리자 사용자 : Q&A와 Admin 버튼 구현과 Admin 버튼 클릭시 이전에 만들었던 관리자 마이페이지로 들어가도록 구현
> feat [박근수] : 로그인한 관리자 사용자가 메인페이지 Footer에서 Admin 클릭시 보여지는 관리자 페이지 UI [ZTZ-WEB-UI100]

- ztz_process/src/main/java/kr/eddi/ztz_process/repository/order/OrderInfoRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/order/PaymentRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/order/OrderServiceImpl.java
- orderInfo PaymentState enum 타입 변경적용에 따른 수정
> fix:[박진주]관리자 회원의 매출조회 시스템[ZTZ-PROCESS57]

- ztz_app/lib/components/my_page/board/modify_question_form.dart
- ztz_app/lib/components/my_page/board/question_board_list.dart
- ztz_app/lib/components/my_page/board/register_question_form.dart
- ztz_app/lib/controller/board/board_controller.dart
- ztz_app/lib/controller/board/board_infos/board_info.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/QuestionController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/BoardCategory.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/BoardCategoryType.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/QuestionBoard.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/boards/QuestionRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionServiceImpl.java
- ztz_web/src/components/boards/QuestionModifyForm.vue
- ztz_web/src/store/actions.js
- ztz_web/src/views/boards/QuestionModifyView.vue
**스프링**
- 게시판 전체 읽기, 특정 게시글 읽기 query문 추가
- 게시글 등록 및 수정 시 카테고리타입 확인 기능 수정
**웹**
- 게시글 수정 페이지에 카테고리 추가
- 수정 actions 코드 보완
**앱**
- 게시글 수정 페이지 구현
> feat: [김가람] 사용자가 마이페이지의 1:1문의 게시물에서 수정 버튼 클릭 시 보는 게시물 수정 UI [ZTZ-APP-UI50]

- ztz_app/lib/components/layout/bottom_bar.dart
- ztz_app/lib/components/my_page/my_page_form.dart
- ztz_app/lib/components/my_page/personal_info_management/profile_modify_component.dart
- ztz_app/lib/components/reivew/reivew_card.dart
- ztz_app/lib/components/reivew/review_register/review_modify_component.dart
- ztz_app/lib/components/reivew/review_register/review_register_component.dart
- ztz_app/lib/components/search/product_search_component.dart
- ztz_app/lib/controller/account/member_api.dart
- ztz_app/lib/controller/account/member_modify_infos/modify_profile_info.dart
- ztz_app/lib/controller/product/product_controller.dart
- ztz_app/lib/controller/product/product_infos/product_info.dart
- ztz_app/lib/controller/reivew/review_controller.dart
- ztz_app/lib/pages/my_page/personal_info_management/profile_modify_page.dart
- ztz_app/lib/pages/reivew/review_modify_page.dart
- ztz_app/lib/pages/search/product_search_page.dart
- ztz_app/lib/utility/button_style.dart
- ztz_app/lib/utility/colors.dart
- ztz_app/lib/utility/text_field_decoration.dart
- ztz_app/lib/utility/text_styles.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/products/ProductsController.java
- 리뷰 수정 삭제 오류해결
- 개인정보 수정 완료
- 검색 UI완료
> feat : [최재민] 리뷰 수정,삭제, 오류 해결

- ztz_process/src/main/java/kr/eddi/ztz_process/service/order/OrderServiceImpl.java
- ztz_web/src/components/mypage/OrderManagement.vue
- ztz_web/src/store/actions.js
- [O]  주문 관리에 3개월, 6개월, 1년 버튼 컴포넌트 UI 구현
- [O]  해당 주문내역들에 대한 조회 메소드 구현
- [O]  해당 주문내역들에 대한 form 및 view에 메소드 적용
- [O]  라우터 연결
> feat [박근수] : 로그인한 사용자가 마이페이지에 주문관리 클릭시 해당 개월 내역의 버튼 컴포넌트 UI [ZTZ-WEB-…UI103] + 해당 주문날짜 출력 코드 수정

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/products/ReviewController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsServiceImpl.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ReviewService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ReviewServiceImpl.java
- ztz_web/src/components/mypage/MyPageReviewCard.vue
- ztz_web/src/components/order/CartForm.vue
- ztz_web/src/views/account/SignInView.vue
**작업내역**
- 리뷰 수정 시 기존의 원본 이미지 파일 삭제
- 등록 상품 수정 시 기존의 원본 이미지 파일 삭제
- 장바구니 페이지 정렬 무너짐 수정
- 로그인 실패 시 alert창 문구 수정
- 리뷰 등록 시스템 코드 수정
> feat: [김가람] 사용자가 작성한 리뷰 수정 시 업로드된 원본 파일을 수정하는 시스템[ZTZ-PROCESS90]

- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ReviewServiceImpl.java
> fix: [김가람] 리뷰 총 평점이 NaN인 경우 0을 반환하도록 코드 수정[ZTZ-PROCESS63]

- ztz_app/lib/components/main_page_components/main_component.dart
search controller 불러오는 코드 추가했습니다.
controller를 통해 추천 키워드를 불러와야 해서 해당 코드 누락으로 추천키워드가 안나왔던 것 같습니다.
> chore: [임보경] SearchController 불러오는 코드 추가

- ztz_app/lib/components/category/category_form.dart
- ztz_app/lib/components/main_page_components/main_component.dart
- ztz_app/lib/components/my_page/favorite/my_favorite_product_card.dart
- ztz_app/lib/components/my_page/favorite/my_favorite_product_component.dart
- ztz_app/lib/components/my_page/my_page_form.dart
- ztz_app/lib/components/my_page/reservation_management/my_reservation_list_card.dart
- ztz_app/lib/components/my_page/reservation_management/my_reservation_modify_form_component.dart
- ztz_app/lib/components/my_page/review_management/writable_review_list_card.dart
- ztz_app/lib/components/order/cart_list_item.dart
- ztz_app/lib/components/product/product_detail/prdouct_buy_modal_component.dart
- ztz_app/lib/components/tour/foundry_page_list_card.dart
- ztz_app/lib/components/tour/reservation_detail/reservation_form_component.dart
- ztz_app/lib/pages/my_page/personal_info_management/profile_modify_page.dart
- ztz_app/lib/pages/tour/foundry_detail_page.dart
- ztz_app/lib/pages/tour/foundry_page.dart
- ztz_app/lib/pages/tour/reservation_payment_result.dart
- ztz_web/src/components/mypage/MyFavoriteForm.vue
- ztz_web/src/components/mypage/MyPageDeliverySection.vue
- ztz_web/src/components/mypage/MyPageNaviTabs.vue
- ztz_web/src/components/mypage/MyPageProfileModify.vue
- ztz_web/src/components/mypage/MyPageReviewCard.vue
- ztz_web/src/components/mypage/MyPageReviewForm.vue
- ztz_web/src/components/mypage/OrderManagement.vue
- ztz_web/src/components/products/review/ProductReviewContents.vue
- ztz_web/src/components/products/review/ProductReviewForm.vue
- ztz_web/src/components/products/review/ReviewModifyForm.vue
- ztz_web/src/components/products/review/ReviewRegisterForm.vue
**작업내역**
- 웹 마이페이지 리뷰 리스트에 주문 번호 추가 및 UI 수정
- 앱 메인페이지와 카테고리에 찜 순위별 상품 페이지 연결 
- 앱 양조장 리스트 페이지 UI 수정
- 앱 마이페이지 양조장 예약 수정, 취소 시 페이지 이동 경로 수정
- 양조장 예약 완료 후 페이지 이동 경로 수정
> add: [김가람] 메인페이지와 카테고리에서 찜 순위별 상품 페이지 연결 및 코드 보완 [ZTZ-APP-UI74]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/products/request/ProductModifyRequest.java
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/products/request/ProductRequest.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/products/Product.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsServiceImpl.java
- ztz_web/src/components/order/OrderProductInfo.vue
- ztz_web/src/components/products/ProductCard.vue
- ztz_web/src/components/products/ProductDetailForm.vue
- ztz_web/src/components/products/ProductList.vue
- ztz_web/src/components/products/ProductModifyForm.vue
- ztz_web/src/components/products/ProductRegisterForm.vue
- ztz_web/src/css/products.css
- ztz_web/src/views/products/ProductsView.vue
배송비 정보 삭제
- 웹 해당 정보 입력하거나 출력되는 영역 삭제
- 서비스, 상품 등록 삭제에서 해당 상품 저장하는 코드 삭제
웹 스타일 변경
- 상품 리스트 크기 변경 최소 폰트 16으로 변경
- 로컬 탭 on 되어있는 탭은 스타일 추가
페이지네이션 수정
- 상품이 없는 페이지로 갔다가 상품이 있는 쪽으로 이동하면 페이지가 보이지 않는 현상 발생
- 해결
> feat:[임보경] 배송비 정보 삭제, 페이지네이션 수정, 상품리스트(웹) 스타일 변경

- ztz_app/lib/components/order/cart_list_item.dart
- ztz_app/lib/components/order/order_payment.dart
- ztz_app/lib/components/product/product_detail/prdouct_buy_modal_component.dart
- ztz_app/lib/components/product/product_detail/product_detail_component.dart
- ztz_app/lib/controller/order/order_controller.dart
- ztz_app/lib/controller/product/product_infos/product_info.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/order/CartController.java
> feat: [임보경] 앱에서 직접 구매 버튼 기능 추가

- ztz_app/lib/components/product/product_list/product_list_component.dart
- ztz_app/lib/components/search/product_search_component.dart
- ztz_app/lib/controller/product/product_controller.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/products/ProductsController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/products/ProductsRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsServiceImpl.java
- 상품 리스트에서 페이지 네이션 기능 추가
-추천 검색어 등록시 최근 검색어에 등록되지 않던 버그 수정
> feat: [최재민] 상품 리스트 페이지 네이션 기능 추가

- ztz_process/src/main/java/kr/eddi/ztz_process/entity/products/Product.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/products/ProductInfo.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/order/ItemRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/order/OrderInfoRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/products/ProductsRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsServiceImpl.java
- ztz_process/src/main/java/kr/eddi/ztz_process/utility/product/StringListConverter.java
- ztz_web/src/store/actions.js
- ztz_web/src/views/products/ProductDetailView.vue
- ztz_web/src/views/products/ProductsView.vue
- 작업내역
- 상품삭제 error 수정
- 관리자 매출조회 error 수정
- 메인메뉴 지역필터 다시클릭 시 모든 상품 보이게 수정
- List<String> 컨버터 추가
- boolean 값 db에 0/1로 저장되도록 수정
> fix:[박진주]관리자 회원이 상품 삭제버튼을 클릭하여 상품 삭제하는 시스템[ZTZ-PROCESS35]

- ztz_app/lib/components/my_page/board/question_board_list.dart
- ztz_app/lib/components/my_page/board/register_question_form.dart
- ztz_app/lib/controller/board/board_controller.dart
- ztz_app/lib/controller/board/board_infos/register_question_info.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/QuestionCommentController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/QuestionBoard.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionCommentService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionCommentServiceImpl.java
- ztz_web/src/components/boards/comment/ModifyQuestionCommentForm.vue
- ztz_web/src/components/managerpage/AllQuestionManagement.vue
- ztz_web/src/components/managerpage/ManagerPageQuestionComment.vue
- ztz_web/src/components/mypage/MyPageQuestionComment.vue
- ztz_web/src/components/mypage/MyPageQuestionForm.vue
- ztz_web/src/store/actions.js
**작업내역**
- 엔티티 수정으로 문의 등록 및 수정 시 전달하는 데이터 수정함
> style: [김가람] 1:1문의 등록 및 수정 시 전달하는 데이터 수정 [ZTZ-APP-UI48]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/QuestionCommentController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/QuestionController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/request/BoardsRequest.java
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/request/CommentRequest.java
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/member/MemberController.java
- ztz_process/src/main/java/kr/eddi/ztz_process/controller/products/request/ProductLocalAndTypeRequest.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/BoardAuthority.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/BoardAuthorityType.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/PageCategory.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/PageCategoryType.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/QuestionBoard.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/QuestionComment.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/boards/BoardAuthorityRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/boards/BoardCategoryRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/boards/PageCategoryRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionCommentService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionCommentServiceImpl.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionService.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionServiceImpl.java
- ztz_web/src/components/managerpage/AllReservationDetailSection.vue
- ztz_web/src/components/mypage/MyReservationDetailSection.vue
- ztz_web/src/components/tour/ReservationModifyForm.vue
- 작업내역
- 질문게시판 엔티티에 페이지 카테고리, 읽기권한 카테고리 추가
- 양조장 예약 리스트 관련 웹에서 조회 안되던 데이터 수정
> fix:[박진주] 로그인 회원이 질문 게시판에 게시글을 등록하기 위한 시스템 [ZTZ-PROCESS19]

- ztz_process/src/main/java/kr/eddi/ztz_process/controller/boards/request/BoardsRequest.java
- ztz_process/src/main/java/kr/eddi/ztz_process/entity/boards/QuestionBoard.java
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/boards/QuestionRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/boards/QuestionServiceImpl.java
- ztz_web/src/components/boards/ModifyQuestionBoardForm.vue
- ztz_web/src/components/boards/RegisterQuestionBoardForm.vue
- ztz_web/src/components/mypage/MyPageQuestionForm.vue
- ztz_web/src/store/actions.js
- 1:1문의 등록 및 수정이 안되는 이슈로 웹 및 스프링쪽 코드 수정
> fix: [김가람] 1:1문의 등록 및 수정 코드 수정 [ZTZ-WEB-UI113]

- ztz_web/src/components/mypage/MyPageProfileModify.vue
- ztz_web/src/views/products/ProductModifyView.vue
회원정보 변경 후에 input 안에 변경된 정보가 남아있는 이슈 해결
> fix: [임보경] 회원 정보 변경 후 새로고침 추가

- ztz_web/src/components/tour/FoundryList.vue
- ztz_web/src/store/actions.js
- ztz_web/src/views/tour/PaymentView.vue
> fix: [임보경] 양조장 체험 관리자 예약이 되는 이슈 해결

- ztz_app/lib/components/my_page/board/modify_question_form.dart
- ztz_app/lib/components/my_page/board/register_question_form.dart
- ztz_app/lib/controller/board/board_controller.dart
- ztz_app/lib/controller/board/board_infos/register_question_info.dart
- ztz_app/lib/pages/my_page/modify_address_page.dart
- 앱 1:1문의 등록 및 수정 시 비밀글 여부를 체크하는 기능 추가
- 마이페이지 배송지 관리에서 배송지 수정 후 페이지 새로고침 추가
> update: [김가람] 1:1문의 등록 시 비밀글 여부를 체크하는 기능 추가 [ZTZ-APP-UI46]

- ztz_app/lib/components/account/login_component.dart
- ztz_app/lib/components/my_page/board/modify_question_form.dart
- ztz_app/lib/components/my_page/order_management/order_detail_management_component.dart
- ztz_app/lib/components/my_page/order_management/order_refund_modal_component.dart
- ztz_app/lib/components/my_page/review_management/written_review_component.dart
- ztz_app/lib/components/order/order_payment_result.dart
- ztz_app/lib/components/product/product_detail/prdouct_buy_modal_component.dart
- ztz_app/lib/components/reivew/product_review_component.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ProductsServiceImpl.java
> fix: [김가람] 장바구니 이동 후 뒤로가기 눌렀을때 팝업창이 유지되는 이슈 수정[ZTZ-APP-UI 59]

- ztz_web/src/components/boards/QuestionListForm.vue
- ztz_web/src/components/boards/QuestionRead.vue
- ztz_web/src/components/boards/comment/QuestionCommentList.vue
- ztz_web/src/components/boards/comment/QuestionCommentRegisterForm.vue
- ztz_web/src/views/boards/QuestionReadView.vue
- Q&A 게시판에서 관리자가 댓글을 등록, 수정 및 삭제 가능
- Q&A 게시판 리스트 및 게시물 읽기에서 사용자 이름 마스킹 처리
> fix: [김가람] Q&A게시판에서 관리자가 댓글을 등록할 수 있는 UI 수정 [ZTZ-WEB-UI75]

- ztz_app/lib/components/product/product_detail/prdouct_buy_modal_component.dart
- ztz_app/lib/components/product/product_detail/product_info_component.dart
- ztz_app/lib/pages/order/cart.dart
- 비회원이 장바구니에서 구매 버튼 클릭 시 로그인이 필요하다는 모달창 + 로그인 페이지로 이동
- 비회원이 상품상세페이지에서 바로구매 버튼 클릭 시 로그인이 필요하다는 모달창 + 로그인 페이지로 이동
> update: [김가람] 비회원이 장바구니에서 구매 버튼 클릭 시 로그인페이지로 이동 [ZTZ-APP-UI38]

- ztz_app/lib/components/reivew/reivew_card.dart
- ztz_app/lib/components/search/product_search_component.dart
- ztz_process/src/main/java/kr/eddi/ztz_process/repository/boards/QuestionCommentRepository.java
- ztz_process/src/main/java/kr/eddi/ztz_process/service/products/ReviewServiceImpl.java
- ztz_web/src/components/order/OrderInfoForm.vue
- [fix : [최재민] 검색 후 결과나오기 전 자판 입력창이 닫힐때 노란색 사이즈 랜더링 오류수정]
- [fix : [최재민] 다른 사람이 작성한 리뷰의 작성자 이름이 보이던 현상 수정]
- [fix : [최재민] 장바구니에서 바로구매시 장바구니상품이 삭제가 안되던 현상 수정]
- [fix : [최재민] 리뷰평점이 소수점 2자리 이하까지 나오던 현상 수정]
> fix :[최재민] 통합 테스트 오류 수정

- ztz_app/lib/components/reivew/reivew_card.dart
- ztz_app/lib/components/reivew/review_register/review_modify_component.dart
- ztz_app/lib/pages/reivew/review_modify_page.dart
- 리뷰 수정 시 기존 리뷰 정보를 불러오도록 코드 수정
> update: [김가람] 리뷰 수정 시 기존 리뷰 정보를 불러오는 UI 추가 [ZTZ-APP-UI78]

- ztz_web/src/components/main/MainPageProductList.vue
- 등록된 상품이 많아짐에 따라 캐러셀 상품 개수 제한
> add: [김가람] 메인페이지 캐러셀 상품 개수 제한 추가 [ZTZ-WEB-UI70]
